# Generated by Django 5.2.10 on 2026-04-09 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('sales', 'Historical Sales'), ('inventory', 'Historical Inventory'), ('weather', 'Weather Data'), ('events', 'Local Events')], max_length=50)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historical Data',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
