# Generated by Django 5.2.10 on 2026-04-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_restock_suggestion_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='restock_override_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('hot_drinks', 'Hot Drinks'), ('cold_drinks', 'Cold Drinks'), ('pastries', 'Pastries'), ('desserts', 'Desserts'), ('add_ons', 'Add-ons'), ('other', 'Other')], default='hot_drinks', max_length=50),
        ),
    ]
