# Generated by Django 5.2.10 on 2026-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_zone_populationrecord_is_manually_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_rate', models.FloatField(default=1.2, help_text='Average births per household')),
                ('death_rate', models.FloatField(default=0.8, help_text='Average deaths per 100 population')),
                ('migration_rate', models.FloatField(default=0.5, help_text='Migration factor')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
