# Generated by Django 5.2.10 on 2026-04-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_simulationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationsettings',
            name='birth_rate',
        ),
        migrations.RemoveField(
            model_name='simulationsettings',
            name='death_rate',
        ),
        migrations.RemoveField(
            model_name='simulationsettings',
            name='migration_rate',
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='customer_arrival_rate',
            field=models.FloatField(default=1.2, help_text='Average new customers per hour'),
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='customer_attrition_rate',
            field=models.FloatField(default=0.5, help_text='Rate at which customers leave the shop'),
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='order_demand_factor',
            field=models.FloatField(default=0.8, help_text='Likelihood of placing an order'),
        ),
    ]
