# Generated by Django 5.2.10 on 2026-04-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_simulationsettings_birth_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='address',
        ),
        migrations.RemoveField(
            model_name='household',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='household',
            name='house_number',
        ),
        migrations.AddField(
            model_name='household',
            name='capacity',
            field=models.IntegerField(default=4, help_text="Number of seats if it's a table"),
        ),
        migrations.AddField(
            model_name='household',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='household',
            name='location_id',
            field=models.CharField(default='T00', help_text='Table number or Shelf ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(choices=[('counter', 'Counter'), ('seating', 'Seating Area'), ('pickup', 'Pickup Zone'), ('kitchen', 'Kitchen'), ('outdoor', 'Outdoor Terrace')], default='counter', max_length=100, unique=True),
        ),
    ]
