# Generated by Django 5.2.10 on 2026-04-09 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_household_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Arrival', 'Customer Arrival'), ('Departure', 'Customer Departure'), ('Order', 'Order Placed'), ('Waitlisted', 'Added to Waitlist'), ('Feedback', 'Guest Feedback Received')], max_length=20)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True, help_text="e.g. 'Standard Table', 'Loyalty App User'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_events', to='common.populationrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='LifeEvent',
        ),
    ]
