# Generated by Django 5.2.10 on 2026-04-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_shopevent_delete_lifeevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('Sales', 'Historical Sales'), ('Footfall', 'Customer Count'), ('Feedback', 'Guest Satisfaction')], max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='historical_data/')),
                ('record_count', models.IntegerField(default=0)),
                ('is_used_for_training', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='holiday_multiplier',
            field=models.FloatField(default=2.5, help_text='Traffic boost during holidays'),
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='model_last_trained',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='model_version',
            field=models.CharField(default='v1.0.0-base', max_length=50),
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='prediction_model_enabled',
            field=models.BooleanField(default=True, help_text='Use AI for forecasting'),
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='promo_event_multiplier',
            field=models.FloatField(default=2.0, help_text='Traffic boost during active promos'),
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='weekday_multiplier',
            field=models.FloatField(default=1.0, help_text='Traffic boost for weekdays'),
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='weekend_multiplier',
            field=models.FloatField(default=1.5, help_text='Traffic boost for weekends'),
        ),
    ]
