# Generated by Django 5.2.10 on 2026-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_historicaldata_simulationsettings_holiday_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('scheduled_time', models.CharField(help_text='e.g., 08:00 - 12:00', max_length=100)),
                ('node_id', models.CharField(default='Node_01', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
