# Generated by Django 5.2.10 on 2026-05-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_operationalschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalschedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Aborted', 'Aborted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
