# Generated by Django 5.2.10 on 2026-05-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_operationalschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='area_type',
            field=models.CharField(choices=[('table', 'Dining Table'), ('bar', 'Bar Counter'), ('booth', 'Booth'), ('pickup', 'Pickup Area'), ('storage', 'Storage Area')], default='table', max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='is_reservable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='household',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='household',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='household',
            name='section_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
